baseURL = "https://wiki.ste332.com"
languageCode = "en-us"
title = "Ste332 Wiki"
theme = "hermit"

[author]
  name = "the prepared dot org"

[[params.social]]
    name = "twitter"
    url = "https://twitter.com/the_prepared"

# Uncomment when we wants multiple pages

[menu]
  [[menu.main]]
    name = "About"
    url = "about/"
    weight = 20
